---
apiVersion: v1
kind: Service
metadata:
  name: rttest-ktm
  labels:
    app: rttest-ktm
spec:
  clusterIP: None
  selector:
    app: rttest-ktm
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rttest-ktm
spec:
  serviceName: rttest-ktm
  selector:
    matchLabels:
      app: rttest-ktm
  replicas: 1
  template:
    metadata:
      labels:
        app: rttest-ktm
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - agent
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: rttest-ktm
        image: david62243/rttest-mon:20190718
        command:
          - sh
          - -c
          - cd /opt/rttest
          - java -cp target/rttest.jar com.esri.rttest.mon.KafkaTopicMon gateway-cp-kafka:9092 planes3
        imagePullPolicy: Always
      #nodeSelector:
      #  func: test
