---
apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  type: ClusterIP
  selector:
    app: es
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: es-0
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: es-0
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: es-1
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: es-1
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: es-2
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: es-2
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
