---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
 name: px-db-rf1-sc
provisioner: kubernetes.io/portworx-volume
allowVolumeExpansion: true
parameters:
 repl: "1"
 priority_io: "high"
 io_profile: "db"
 disable_io_profile_protection: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: esrally-ss
  labels:
    app: esrally-ss
spec:
  ports:
  clusterIP: None
  selector:
    app: esrally-ss
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esrally-ss
spec:
  serviceName: esrally-ss
  selector:
    matchLabels:
      app: esrally-ss
  replicas: 1
  template:
    metadata:
      labels:
        app: esrally-ss
    spec:
      containers:
      - env:
        - name: network.host
          value: 0.0.0.0
        name: esrally-ss
        image: satchpx/esrally:v0.1
        command:
        - sh
        - -c
        - "exec tail -f /dev/null"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /opt/rally
          name: rally-data
  volumeClaimTemplates:
  - metadata:
      name: rally-data
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 200Gi
      storageClassName: px-db-rf1-sc