 kind: StorageClass
 apiVersion: storage.k8s.io/v1beta1
 metadata:
   name: portworx-sc-repl1
 provisioner: kubernetes.io/portworx-volume
 parameters:
   repl: "1"
   priority_io: "high"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fio
spec:
  selector:
    matchLabels:
      app: fio
  serviceName: "fio"
  replicas: 1
  template:
    metadata:
      labels:
        app: fio
    spec:
      schedulerName: stork
      terminationGracePeriodSeconds: 10
      containers:
      - name: fio
        image: satchpx/fio-tester:latest
        volumeMounts:
        - name: mnt
          mountPath: /mnt
  volumeClaimTemplates:
  - metadata:
      name: mnt
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "portworx-sc-repl1"
      resources:
        requests:
          storage: 100Gi