#!/usr/bin/env bash

printUsage() {
    cat <<EOEG
Usage: $0 
    -p <number of kafka partitions>
    -c <count> [Optional, Default: 25]
    -k <kubeconfig> [Optional, Default: /root/.kube/config]
Example:
    run-suite -o start -t planes6 # To start the test
    run-suite -o stop # To stop the test
EOEG
}

while getopts "h?:c:p:k:" opt; do
    case "$opt" in
    h|\?)
        printUsage
        exit 0
        ;;
    c)  COUNT=$OPTARG
        ;;
    p)  PARTN=$OPTARG
        ;;
    k)  KC=$OPTARG
        ;;
    :)
        echo "[ERROR] Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
    default)
       printUsage
       exit 1
    esac
done

if [ -z ${COUNT} ]; then
    COUNT=25
fi

if [ -z ${PARTN} ]; then
    PARTN=10
fi

DIRNAME=`dirname $0`
for iter in $(seq 1 $COUNT); do
    echo "[INFO]: Begin iteration ${iter}"

    # start the test
    echo "[INFO]: Starting the test..."
    eval "${DIRNAME}/run-test -o start -p ${PARTN}"
    sleep 780
    echo "[INFO]: Completed iteration ${num}"
    echo "[Kafka Topic Monitor Logs]"
    kubectl logs rttest-ktm-0
    echo "-------------------------------------------------------------------------"
    echo "[Elasticsearch Index Monitor Logs]"
    kubectl logs rttest-eim-0
    echo "-------------------------------------------------------------------------"

    echo "[INFO]: Begin tear down"
    eval "${DIRNAME}/run-test -o stop -p ${PARTN}"
    sleep 120
    echo "[INFO]: Tear down complete"
done